CATEGORIES = {
    'Adult': 'Adult',
    'Recreation': 'Arts & Entertainment',
    'Autos': 'Autos & Vehicles',
    'Fitness': 'Beauty & Fitness',
    'Books': 'Books & Literature',
    'Business': 'Business & Industrial',
    'Computers': 'Computers & Electronics',
    'Finance': 'Finance',
    'Food': 'Food & Drink',
    'Games': 'Games',
    'Health': 'Health',
    'Hobbies': 'Hobbies & Leisure',
    'Home': 'Home & Garden',
    'Internet': 'Internet & Telecom',
    'Education': 'Jobs & Education',
    'Law': 'Law & Government',
    'News': 'News',
    'Communities': 'Online Communities',
    'Society': 'People & Society',
    'Pets': 'Pets & Animals',
    'Real Estate': 'Real Estate',
    'Reference': 'Reference',
    'Science': 'Science',
    'Sensitive': 'Sensitive Subjects',
    'Shopping': 'Shopping',
    'Sports': 'Sports',
    'Travel': 'Travel',
}
